import { 
  Settings, 
  Settings2,
  Trash, 
  Copy, 
  Link, 
  Search, 
  Moon, 
  Sun, 
  Monitor, 
  Laptop, 
  Smartphone, 
  Globe,
  MoreHorizontal,
  MoreVertical,
  Power,
  ToggleLeft,
  ToggleRight,
  Calendar,
  Target
} from "lucide-react";

export {
  Settings as UtilitySettingsIcon,
  Settings2 as ConfigIcon,
  Trash as UtilityDeleteIcon,
  Copy as CopyIcon,
  Link as UtilityLinkIcon,
  Search as UtilitySearchIcon,
  Moon as DarkModeIcon,
  Sun as LightModeIcon,
  Monitor as DesktopIcon,
  Laptop as LaptopIcon,
  Smartphone as MobileIcon,
  Globe as GlobalIcon,
  MoreHorizontal as HorizontalMenuIcon,
  MoreVertical as VerticalMenuIcon,
  Power as PowerIcon,
  ToggleLeft as ToggleOffIcon,
  ToggleRight as ToggleOnIcon,
  Calendar as CalendarIcon,
  Target as TargetIcon
};
